[ExampleModLib]
    id = 'examplemodlib'
    name = 'ExampleModLib'
    group = 'example.examplemodlib'

    [ExampleModLib.meta]
        displayName = 'Example Mod Library'
        description = 'An example library for example mods'

[ExampleModLibTest]
    id = 'examplemodlibtest'
    name = 'ExampleModLibTest'
    group = 'example.examplemodlib.test'

    [ExampleModLibTest.meta]
        displayName = 'Example Mod Library Test'
        description = 'A test mod for the Example Mod Library'

[ExampleMod1]
    id = 'examplemod1'
    name = 'ExampleMod1'
    group = 'example.examplemod1'

    [ExampleMod1.meta]
        displayName = 'Example Mod 1'
        description = 'The first example mod'

[ExampleMod2]
    id = 'examplemod2'
    name = 'ExampleMod2'
    group = 'example.examplemod2'

    [ExampleMod2.meta]
        displayName = 'Example Mod 2'
        description = 'The second example mod'

[minecraft]
    version = '1.13'
    range = '[1.13]'

    [minecraft.mappings]
        channel = 'snapshot'
        version = '20180921-1.13'

    [minecraft.forge]
        name = 'forge'
        group = 'net.minecraftforge.test'
        version = '1.13-24.0.128-userdev-check-path-exists'
        range = '[24,)'

    [minecraft.modLoader]
        loader = 'javafml'
        range = '[24,)'
